### ISSUE TITLE
Incorrect left-to-right order of operations

### ISSUE THREAD

**Issue by mrfigg** [Morgul/rpgdice#4]
I ran a couple of basic order of operations tests with version `2.0.0-rc.2` and got some illogical results.

Input: `2+8-2+8`
Expected output: `16`
Generated output: `0`

Input: `1-(1+1)+1`
Expected output: `0`
Generated output: `-2`

Both tests seem to be going outside-in instead of left-to-right.

**Comment by Morgul** [comment]
I think you're right, evaluation is outside-in, due to how we're generating the AST. It's a little surprising that in the years of my using this, I've never caught that. I'll have to give this some thought; I'd like to find a solution that doesn't involve too drastic a change. 

Out of curiosity, could you test in v1.3.0? I'll bet it's just as broken. If it isn't, then the problem's likely the fix to #1.

**Comment by mrfigg** [comment]
Yep, same results in version `1.3.0`.

**Comment by mrfigg** [comment]
I found this, looks like it might help;
https://stackoverflow.com/questions/24174714/how-do-you-build-a-left-associative-operator-tree-using-peg-js

**Comment by Morgul** [comment]
closed by 6e6851d916cf809c390ecb2fda3ddd0e6cf323a6.
